### ISSUE TITLE
UNANNOUNCED RELEASE PAGE APPEARS ON CURSEFORGE

### ISSUE THREAD

**Issue by MCUmbrella** [MCUmbrella/ATG-Modified#2]
In 'Traffic' page I found the visit from Google and CurseForge. I am here to say I NEVER POSTED ANY PAGE OR SAY ANYTHING ABOUT ATG-MODIFIED IN CURSEFORGE AND I NEVER RECIVED ANY NOTICE BEFORE AND AFTER THAT PAGE APPEARED IN CURSE FORGE.

If the publisher is not bad he should indicate that I am also among the developers of this mod AND NOT IGNORE ME FROM THE MEMBERS LIST.

Except for my Github page and all pages that I allow to forward, NO PAGES WILL GET ANY SUOOPRT FROM ME.

And I also heard that if the downloads reaches a certain amount, CurseForge will pay them? SHAMEFUL BEHAVIOR.

**Comment by furtabs** [comment]
For clarification 

A: I gave you ownership back it was a test to see if the mod would get on curse again

B:I don’t get the points 100% was going to the original author to hope that we could get it back on curse.

C: I did it because The mod has been taken down twice but neither times TTFTCUTS was credited
